### ISSUE TITLE
Licensing Problem

### ISSUE THREAD

**Issue by RonnyWeiss** [rhinterndorfer/APEX-Highcharts#1]
Hello

Highcharts are only free for personal use could you please add this to your license? 

Kind Regards

Ronny

**Comment by rhinterndorfer** [comment]
I have update the license and mentioned that highcharts needs extra licensing for commercial use.
The plugin itself also contains a attribute the user must explicitly set to approve that she/he has obtained a highcharts license.
Thanks for the hint.

**Comment by RonnyWeiss** [comment]
Thank you for adding this to license so everybody can read that its Not only FREE for Private use.

Maybe would be Vetter to add this to description in apex.world json or in readme or maybe change the libary to a FREE one e.g. D3, would that be an option?

Kind regards 

Ronny

**Comment by rhinterndorfer** [comment]
I have also added a hint in the apex.world json.
I wanted to explicitly address highcharts for this plugin therefore D3 is not an option.
I have a customer who uses highcharts and I think this will help us and maybe others to implement highcharts quickly.
I know that you are developing a D3 charts plugin for APEX. If I have some time I will throw a deeper look on it and maybe I can learn something for my plugins.
Thanks for your feedback.

**Comment by RonnyWeiss** [comment]
Ah ok now I understand. Thank you for quick answers. Highcharts are Really cool I would also like to use them but licensing is a big problem. Thats why I use billboard/D3 js. I use billboard ja because it makes D3 mich easier but the goos Thing about D3 is that you can Do so much e.g. also world map like in Material dashboard and you can customize everything. But If you use directly d3js ist very much you need to Do by your own.  But thank you for giving the World your Code for free and I hope many will use your Plugins. Thank you and have a nice week

Ronny
